### ISSUE TITLE
Support escapes and proper numbers

### ISSUE THREAD

**Issue by quintesse** [rmnbhm/jsonwheel#5]
The current parser doesn't properly support all valid escapes and also doesn't support all valid floating point numbers:

- officially only `"`, `/`, `\` and the letters b, f, n, r, t, u are allowed for escapes. But perhaps you don't mind being more flexible than the standard, but
- the parser needs to support `\uxxxx` to be able to accept all valid JSON documents, and
- numbers without a `.` can also be valid numbers, eg. `5e10` is a valid number (and would have to be parsed as a Double).

It's probably a good idea to take a look at syntax diagram here: https://www.json.org/json-en.html

There is also a test suite that's very useful: https://www.json.org/JSON_checker (at the bottom where it says "test suite")

**Comment by romanboehm** [comment]
Hey there,

First of all: thanks for taking an interest in JsonWheel! First issue not raised by me. ;)

> - officially only `"`, `/`, `\` and the letters b, f, n, r, t, u are allowed for escapes. But perhaps you don't mind being more flexible than the standard, but

Yes, to put it shortly: I have no problem being more lenient than the spec if it saves some lines. That's why my impl is very bare bones right now. But I'll look into it!

> - the parser needs to support `\uxxxx` to be able to accept all valid JSON documents, and

Same: Let me look into that and see if I can fit it in. Seems like it's a common case (I suppose this is about non-ASCII chars).

> - numbers without a `.` can also be valid numbers, eg. `5e10` is a valid number (and would have to be parsed as a Double).


There's already #2 for that. I'm not happy with the number parsing either atm. 🙂

> There is also a test suite that's very useful: https://www.json.org/JSON_checker (at the bottom where it says "test suite")

Thank you, I was actually looking for something exactly like that. I referenced json.org many times, but didn't come across this test suite! Perfect!

All that being said: Please understand that I am absolutely not aiming for 100% spec compliance. I want to cover the 80% mainly. If I can fit in more while staying below, let's say, 250 lines, I'll consider it.

Best,
Roman

**Comment by quintesse** [comment]
> Hey there,
> 
> First of all: thanks for taking an interest in JsonWheel! First issue not raised by me. ;)

Hehe, I'm one of the jbang devs, that's how I found about it.

> 
> > * officially only `"`, `/`, `\` and the letters b, f, n, r, t, u are allowed for escapes. But perhaps you don't mind being more flexible than the standard, but
> 
> Yes, to put it shortly: I have no problem being more lenient than the spec if it saves some lines. That's why my impl is very bare ones right now. But I'll look into it!

Yeah, that's what I thought, perfectly reasonable.

> 
> > * the parser needs to support `\uxxxx` to be able to accept all valid JSON documents, and
> 
> Same: Let me look into that and see if I can fit it in. Seems like it's a common case (I suppose this is about non-ASCII chars).

Well this would mean that there's a certain class of valid documents that you wouldn't be able to parse. But that might be okay for your use-case of course. :slightly_smiling_face: 

> 
> > * numbers without a `.` can also be valid numbers, eg. `5e10` is a valid number (and would have to be parsed as a Double).
> 
> There's already #2 for that. I'm not happy with the number parsing either atm. slightly_smiling_face

Ah, I hadn't seen that :+1: 

> 
> > There is also a test suite that's very useful: https://www.json.org/JSON_checker (at the bottom where it says "test suite")
> 
> Thank you, I was actually looking for something exactly like that. I referenced json.org many times, but didn't come across this test suite! Perfect!

Yeah, it's somewhat hidden. I only found it the first time because the simple-json code mentions it.

> 
> All that being said: Please understand that I am absolutely not aiming for 100% spec compliance. I want to cover the 80% mainly. If I can fit in more while staying below, let's say, 250 lines, I'll consider it.

Understood.

> 
> Best, Roman

Good luck!

**Comment by romanboehm** [comment]
FYI: I created #6 and #7 (in addition to #2), so one can track the progress of each of the items individually. I'm going to close here as I think all concerns will sufficiently be covered through those issues (at least those I want to address in the first place 😄).

Best,
Roman
